# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target 'ScanQR' do
  pod 'AFNetworking', '~> 2.5'
  pod 'ORStackView', '~> 2.0'
  pod 'TesseractOCRiOS', '4.0.0'
end

target 'ScanQRTests' do

end

